apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: resource-watcher
spec:
  schedule: '*/1 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ggoods-hapi-cronjob
              image: ${DOCKER_REGISTRY}/${IMAGE_NAME_HAPI}:${VERSION}
              args:
                - /bin/sh
                - -c
                - node /app/src/utils/resource-watcher.util.js;
          restartPolicy: Never
